/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Car = IDL.Record({
  'id' : IDL.Nat,
  'zeroToSixty' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'brand' : IDL.Text,
  'topSpeed' : IDL.Nat,
  'horsepower' : IDL.Nat,
  'engine' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'timestampNanos' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
  'getInquiryById' : IDL.Func([IDL.Nat], [IDL.Opt(ContactForm)], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateInquiry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'zeroToSixty' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'brand' : IDL.Text,
    'topSpeed' : IDL.Nat,
    'horsepower' : IDL.Nat,
    'engine' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
    'getInquiryById' : IDL.Func([IDL.Nat], [IDL.Opt(ContactForm)], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateInquiry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };